# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            Thiago Marzag√£o
tagline:          'A Jekyll theme'
description:      'data, code, etc'
url:              http://thiagomarzagao.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0
comments:         true

github:
  repo:           https://github.com/poole/hyde
