# Dependencies
highlighter:      rouge
markdown:         kramdown
kramdown:
  input: GFM

# Permalinks
permalink:        /:year-:month-:day-:title/

# Setup
title:            Thiago Marzag√£o
tagline:          'A Jekyll theme'
description:      'data, code, etc'
url:              http://thiagomarzagao.github.io
baseurl:          ""

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

#gems:             [jekyll-paginate]
paginate:         5

# Custom vars
#version:          2.1.0
comments:         true

github:
  repo:           https://github.com/poole/hyde
